image: base/devel

before_script:
  - pacman -Sy archiso --noconfirm

pages:
  stage: deploy
  script:
    - ./build.sh
    - mv out public
    - cd public
    - md5sum *.iso > md5sum.txt
    - sha1sum *.iso > sha1sum.txt
  artifacts:
    name: "firerain-iso"
    paths:
      - public
  only:
    - master
